### ISSUE TITLE
Question: using the labextension of jupyter_conda

### ISSUE THREAD

**Issue by fcollonval** [TheSnakePit/mamba-navigator#8]
Hey,

I got a question on my mind. [jupyter_conda](https://github.com/fcollonval/jupyter_conda) is now supporting mamba. And as the JupyterLab extension is a React component injected within a lumino Panel (with only some settings coming from JLab), I wonder if it could be interesting to have a standalone mode for that (maybe spinning something on top of `jupyter_server`). And from there we could add the features included in this project?

**Comment by SylvainCorlay** [comment]
Hey @fcollonval, nice to see you here!

Many thanks for implementing the support for mamba in jupyter_conda! We noticed earlier last week, and we already tried!

I think that it would make sense for the projects to reuse the same front-end components. We were actually thinking of making the front-end to the mamba navigator a remix of JupyterLab plugins into a standalone implementation.

Maybe we could abstract whether this is built upon a jupyter server or another backend in the front-end through some common interface?

**Comment by fcollonval** [comment]
Thanks Sylvain for the feedback.

I started to describe the [REST API](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/fcollonval/jupyter_conda/master/jupyter_conda/rest_api.yml) for `jupyter_conda`. Is it what you are interested in? Or are you interested in a higher JS interfaces calling the REST API as described in that [tokens.ts](https://github.com/fcollonval/jupyter_conda/blob/master/labextension/src/tokens.ts) file?

About the backend, just to be sure I got it correctly, you may end up using some other backend technology than Jupyter (i.e. Tornado). So reusing that part of the code is of less importance.

**Comment by jtpio** [comment]
Thanks @fcollonval!

For reference, a minimal lab-based skeleton app was added in https://github.com/TheSnakePit/mamba-navigator/pull/9.

It is mostly inspired by the [JupyterLab app example](https://github.com/jupyterlab/jupyterlab/tree/master/examples/app), but should provide the basic structure to add new plugins.

It would be interesting if we could indeed share most of the UI with `jupyter_conda`!

> About the backend, just to be sure I got it correctly, you may end up using some other backend technology than Jupyter (i.e. Tornado). So reusing that part of the code is of less importance.

Wouldn't it be possible to reuse some of the `jupyter_conda` server extension handlers?

**Comment by fcollonval** [comment]
Nice work with the basis app. It will indeed be a good starting point.

The may question for the frontend is how do you want it to be integrated in the navigator. For now the activation function requires:

```
  app: JupyterFrontEnd,
  palette: ICommandPalette,
  menu: IMainMenu,
  restorer: ILayoutRestorer,
  settingsRegistry: ISettingRegistry
```

I guess that `palette` and  `menu` should be optional to support the navigator. What about the layout restorer (it seems that it could be optional too).

> Note: There is also a secondary [entrypoint](https://github.com/fcollonval/jupyter_conda/blob/a7fd182a6b6a47a7ca48b545ba946e2937fcf4b1/labextension/src/index.ts#L166) that should be dropped for the navigator. It's purpose is to check that all environments contains some specific packages (to ensure widgets to work by having the Python module matching the included JS package). It anyway should be dropped for v3.

> Wouldn't it be possible to reuse some of the `jupyter_conda` server extension handlers?

Sure it would make lots of sense. Anyway, at some point I need to port it to JLab v3 and the new `jupyter_server` :wink:

**Comment by jtpio** [comment]
> I guess that `palette` and `menu` should be optional to support the navigator. What about the layout restorer (it seems that it could be optional too).

Yes exactly. Just opened https://github.com/fcollonval/jupyter_conda/pull/73 for this.

> The may question for the frontend is how do you want it to be integrated in the navigator

A first step could be:

- Either import and use the `CondaEnvWidget` react widget from `jupyter_conda` directly, and manually add it to the `main` area
- Or consume a plugin exposed by `jupyter_conda`, that adds the widget to the JupyterLab areas

Of course we could also reconsider where some of these components should leave (either here or in `jupyter_conda`)

**Comment by SylvainCorlay** [comment]
Why not keeping a command palette in the navigator front end?

**Comment by jtpio** [comment]
> Why not keeping a command palette in the navigator front end?

There can be one in the navigator frontend too. But having it optional shouldn't prevent that.

**Comment by jtpio** [comment]
There is now a Binder that runs the Mamba Navigator as a separate service with `jupyter-server-proxy` alongside JupyterLab:

https://github.com/TheSnakePit/mamba-navigator#try-it-online

It also includes the `jupyterlab_conda` lab extension, so we can easily see how the same components (for now the conda packages manager widget) are used in the different frontends.

@fcollonval :

For now it's possible to iterate on the mamba navigator frontend by using the `jupyter_conda` handlers and the components from `jupyterlab_conda/lib`. If you have any opinion on where things should live (for example in a new repo under the `TheSnakePit` organization) and whether to split components up, feel free to comment here! Additionally we can also setup a quick call to discuss this more.

**Comment by fcollonval** [comment]
@jtpio It makes sense to move [jupyter_conda](https://github.com/fcollonval/jupyter_conda) under the hood of _TheSnakePit_ group. But yes, it would be nice to have a call on this.

**Comment by SylvainCorlay** [comment]
Would love to get on such a call.

Quick thought: this could be a pattern for lab extensions to be both usable in a "standalone" mode and as an extension to e.g. lab.

**Comment by SylvainCorlay** [comment]
Update: we have renamed the "snakepit" organization into "mamba-org".

**Comment by jtpio** [comment]
Today with @fcollonval @SylvainCorlay and @wolfv, we discussed moving [jupyter_conda](https://github.com/fcollonval/jupyter_conda) over to the `mamba-org` organization.

We can then:

- have the `mamba-navigator` frontend and `jupyter_conda` in the same repository
- open and transfer issues to track the next steps
- archive https://github.com/mamba-org/mamba-navigator?

**Comment by fcollonval** [comment]
jupyter_conda has been transfered :wink:

**Comment by fcollonval** [comment]
Thinking over about the merge of mamba-navigator and jupyter_conda. I assume we need to move to a multi-package structure to split the stand-alone part and the extension?

**Comment by jtpio** [comment]
> jupyter_conda has been transfered

Nice, thanks!

> I assume we need to move to a multi-package structure to split the stand-alone part and the extension?

We could indeed setup a `lerna` structure to be able to use local packages for example here:

https://github.com/mamba-org/mamba-navigator/blob/ae20cd86635fc44ae5be36fbe71d07f84dbc5709/src/plugins/navigator/index.ts#L10

**Comment by jtpio** [comment]
Fixed by https://github.com/mamba-org/jupyter_conda/pull/79
